name: Pulumi
on:
  push:
    branches-ignore:
      - main
      
jobs:
  pulumi-preview:
    name: run-pulumi-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: dev
          work-dir: ./cloud_run
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}